#!C:\Users\Adimin\AppData\Local\Programs\Python\Python37\python.exe
print("Content-type:text/html\r\n\r")
print("<html>")
print("<head>")
print("<title>")
print("National Flag")
print("</title>")
print("</head>")
print("<body vlink=blue a link=black>")
print("<center>")
print("<PALIGEN=CENTER>")
print("<FRONT SIZE=40>")
print("Our national flag")
print("</FONT>")
print("</P>")
print("</center>")
print("<br><br>")
print("<ul>")
print("<li><a href='#'>saffron</li>")
print("<li><a href='#'>white</li>")
print("<li><a href='#'>green</li>")
print("</ul>")
print("</body>")
print("</html>")
